### ISSUE TITLE
Question about Dockerize

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018-Spring#80]
Dockerize를 진행하는데 궁금한 점이 있어서 이슈를 남기게 되었습니다.

service_setup.sh는 저희가 따로 구성하는게 아니라 템플릿에 존재하는 스크립트를 그대로 이용하는지요?

그리고 gitctf 스크립트를 통해 docker run 명령어가 실행되면 컨테이너가 어떤 상태여야 하는지 궁금합니다.

예를들어 docker run을 실행하면 container가 Exit상태가 아닌 Up 된 상태에서 service가 돌고 있는 상태로 대기 하여야 하는지요?

감사합니다.

**Comment by seongil-wi** [comment]
(1) Yes, you should use [`setup_service.sh`](https://github.com/KAIST-IS521/2018s-gitctf-script/blob/master/scripts/setup_service.sh) for your service and [`launch_exploit.sh`](https://github.com/KAIST-IS521/2018s-gitctf-script/blob/master/scripts/launch_exploit.sh) for your exploit. 
(2) The service must be still running when you use gitctf.py script, and if it is an exploit, it must be rotated once and shut down immediately.

Note that you cannot control the setup_service.sh and launch_exploit.sh because we will use original version of that.

**Comment by Hexife** [comment]
서비스 확인을 `nc 127.0.0.1 port` 형식으로 진행는 것을 확인했는데,  
실제로 nc를 돌리면 서비스 하는 프로그램의 출력이 확인되어야 하는건가요?

예를 들어 클라이언트-서버 형태의 프로그램에서는 클라이언트의 출력이 확인되어야 하나요?

**Comment by seongil-wi** [comment]
When you see the [`verify_service.py`](https://github.com/KAIST-IS521/2018s-gitctf-script/blob/master/scripts/verify_service.py) script, you can see that verify command is `nc -z 127.0.0.1 port`.
As you can see in the man page of netcat, -z option is exist for just scanning for listening daemons, without sending any data to them. Because [`setup_service.sh`](https://github.com/KAIST-IS521/2018s-gitctf-script/blob/master/scripts/setup_service.sh) run docker with `-d` option, if your docker successfully running on your service, `nc -z 127.0.0.1 port` command will return exist code 0.

**Comment by seongil-wi** [comment]
It's not easy to understand `클라이언트가 데몬을 통해 listening을 하는 방식`. However, `클라이언트가 데몬에 connect를 하는 형식 & 서버가 데몬을 통해 listening을 하는 방식` is more make sense to me. If this is right, yes, your suggestion is right.

**Comment by Hexife** [comment]
제가 표현을 잘 못하고 있는거 같습니다. 번거롭게 해서 죄송합니다. ㅠㅠ

저희가 맡은 프로젝트 기준으로는 Chatting Server와 Chatting Client가 존재하는데, Chatting Client가 따로 배포되는 것이 아니라 Docker 안에서 돌아야 한다고 생각하고 있습니다. 

그래서 저는 Docker 안에서 Chatting Client 와 Chatting Server를 Docker Container안에서 돌리려고 생각 하고 있었습니다. 만약 이런 상황에서 말씀해 주신대로 `Chatting 클라이언트가 데몬에 connect를 하는 형식 & Chatting 서버가 데몬을 통해 listening을 하는 방식`으로 구현하면 Container 안에서는 잘 되겠지만 다른 Container에서 Connection/Exploit 할 때 Client에 붙을 방법이 없다고 생각해서,  `Chatting Client 또한 Daemon에 붙여 외부에서 연결을 할수 있도록 만드는 것`이 맞는 방법인지 여쭤 보고 싶었습니다.

각 팀의 재량일 수도 있지만 잘못된 구현으로 CTF 운영에 피해(?)를 드릴까봐  혹시나 싶어서 여쭤 봅니다.

감사합니다.

**Comment by sangkilc** [comment]
When we say prepare a service, it means a *server* application that listens for a specific port. It is okay to put both client and server into your own "service", but there must be a port bound to an external network.

**Comment by Hexife** [comment]
답변해 주셔서 감사합니다! 궁굼했던 점이 해결되었습니다.

**Comment by sangkilc** [comment]
Closing this issue since @Hexife  is happy about the answer.
